FROM curlimages/curl:latest

# Just for debugging internals and checking that controller
# is working as expected. To find out, what's going on, one
# can try e.g.

# curl localhost:8001/apis
# curl localhost:8001/apis/ahojukka5.com/v1/dummysites


CMD sleep 86400
